#pragma once

namespace ped_data
{
	std::vector<std::string_view> ped_types{
		"PLAYER_0", "PLAYER_1", "NETWORK_PLAYER",
		"PLAYER_2", "CIVMALE", "CIVFEMALE",
		"COP", "GANG_ALBANIAN", "GANG_BIKER_1",
		"GANG_BIKER_2", "GANG_ITALIAN", "GANG_RUSSIAN",
		"GANG_RUSSIAN_2", "GANG_IRISH", "GANG_JAMAICAN",
		"GANG_AFRICAN_AMERICAN", "GANG_KOREAN", "GANG_CHINESE_JAPANESE",
		"GANG_PUERTO_RICAN", "DEALER", "MEDIC",
		"FIREMAN", "CRIMINAL", "BUM",
		"PROSTITUTE", "SPECIAL", "MISSION",
		"SWAT", "ANIMAL", "ARMY"
	};
}
